### ISSUE TITLE
After updating to 0.6.1, the vite project reports an error.

### ISSUE THREAD

**Issue by Daotin** [inocan-group/brilliant-errors#1]
![image](https://user-images.githubusercontent.com/23518990/203227686-2d144aa2-4f4e-4dbe-8587-97c0bc70c24d.png)

```
require() of /root/.jenkins/workspace/1475-001-build-test-html-nginx/app/node_modules/brilliant-errors/node_modules/callsites/index.js from /root/.jenkins/workspace/1475-001-build-test-html-nginx/app/node_modules/brilliant-errors/dist/index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.

Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /root/.jenkins/workspace/1475-001-build-test-html-nginx/app/node_modules/brilliant-errors/node_modules/callsites/package.json.
```

But, When I install the 0.6.0 version separately in the project, everything is fine.

Like this: 
![image](https://user-images.githubusercontent.com/23518990/203228081-f2e3c200-667e-480f-bd09-900004ab9399.png)

But this is not a good way to deal with it, is there any other better way? Thx.

**Comment by eckberg** [comment]
I am having the same issue. Another workaround for me was to force my project to use the brilliant-errors/dist/index.js file instead of brilliant-errors/dist/index.cjs, so I guess there is a problem with either this project or vite, but outside of my knowledge how to fix. 

Can also confirm that downgrading to 0.6.0 fixed the issue.

**Comment by Daotin** [comment]
I found a way to solve it,  package.json can use `overrides` to fix the dependency version (Need npm >= [v8.3](https://github.com/npm/cli/releases/tag/v8.3.0)),  But I don't think it's an elegant solution :<

```json
"overrides": {
    "brilliant-errors": "0.6.0"
}
```

**Comment by yankeeinlondon** [comment]
Yes sorry I just realized this and am going to fix it today. Thanks for mentioning this.

**Comment by yankeeinlondon** [comment]
Version `0.7.1` should fix this as long as you're able to import ESM modules as we only export ESM now due to downstream deps imposing this restriction. For most people this should be fine as ESM is clearly the target going forward but also most build systems can import ESM just fine and transpile to a CJS output.

**Comment by yankeeinlondon** [comment]
I'm going to close this for now but feel free to reopen it if you continue to have issues.
